site_name: 贺老师的学习天地
site_url: https://zh1995.github.io/cswiki/
theme:
  name: material
  language: zh
  palette:
    # Light Mode
      - scheme: default
        primary: light blue
        accent: deep purple
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
    # Dark Mode
      - scheme: slate
        primary: cyan
        accent: deep purple
        toggle:
          icon: material/weather-night
          name: Switch to light mode
  features:
    - navigation.footer
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - footnotes
extra:
  social:
    - icon: fontawesome/brands/github
      name: Github
      link: https://github.com/ZH1995/Cswiki/

copyright: Copyright &copy; 2017 - 2025 ZH1995
plugins:
  - search:
      lang:
        - zh
        - en
  - i18n:
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
          site_name: Teacher He's Study World
          nav_translations:
            前言: Foreword
            必学工具: Productivity Toolkit
            科学上网: GFW
            好书推荐: Book Recommendation
            编程入门: Fundamental Programming
            Python 语言: Python Language
            C 语言: C Language
            计算机系统基础: Computer Systems Principles
            数据库系统: Database Systems

nav:
  - 前言: "index.md"
  - 必学工具:
      - 科学上网: "必学工具/科学上网.md"
      - 信息检索: "必学工具/信息检索.md"
  - 好书推荐: "好书推荐.md"
  - 编程入门:
      - Python 语言:
          - "UCB CS61A: Structure and Interpretation of Computer Programs": "编程入门/Python/CS61A.md"
          - "CS50P: CS50's Introduction to Programming with Python": "编程入门/Python/CS50P.md"
      - C 语言:
          - "Harvard CS50: This is CS50x": "编程入门/C/CS50.md"
          - "Duke University: Introductory C Programming Specialization": "编程入门/C/Duke-Coursera-Intro-C.md"
  - 计算机系统基础:
      - "CMU 15-213: CSAPP": "计算机系统基础/CSAPP.md"
  - 数据库系统:
      - "CMU 15-445: Database Systems": "数据库系统/CMU15445.md"
      - "Stanford CS346: Database System Implementation": "数据库系统/CS346.md"